### ISSUE TITLE
\s-word-\s  not converted to italics as discussed

### ISSUE THREAD

**Issue by GregTheGrate** [gethryn/hyphens#14]
<p class="calibre4">'Tell me, Cynthia,' resumed Mrs Ford, 'how did you do it? I was telling Lord Mountry that I -hoped- I might see my Ogden again soon, but I never really hoped. It seemed too impossible that you should succeed.'</p>

This is in the clean output

**Comment by gethryn** [comment]
Not sure why this doesn't work...
