### ISSUE TITLE
-word- quotation mark

### ISSUE THREAD

**Issue by GregTheGrate** [gethryn/hyphens#15]
Perhaps I'm asking too much, happy to fix manually.  Could be construed either way.  Would prefer italics.  Just Use [i]word[/i] is perfect.  Had to use square brackets as it interpreted my <>i tag and changed "word" to italics.

Clean output
 <p class="calibre4">''Ogden,—dearest!-' said Mrs Ford. 'Very well, Cynthia. Go, Ogden. You will order yourself something substantial, marvel-child?'</p>

Original is <p class="calibre4">'Ogden, -dearest!-' said Mrs Ford. 'Very well, Cynthia. Go, Ogden. You will order yourself something substantial, marvel-child?'</p><br class="calibre1"/>

**Comment by gethryn** [comment]
The punctuation inside the italics is the part that is stopping it working.  I will add ? and ! to the acceptable characters inside - -
