### ISSUE TITLE
whump!-the got missed

### ISSUE THREAD

**Issue by GregTheGrate** [gethryn/hyphens#20]
Looks like any hyhen after any punctuation doesn't work.  We could make a new rule that any - after puntuation, regardless of the word should be an em-dash

**Comment by gethryn** [comment]
What an excellent issue title. Will look tonight

**Comment by GregTheGrate** [comment]
I thought so too
 

Greg
Mobile: 0416-217-027
***@***.*** ***@***.***>
www.notjustnotes.com.au <http://www.notjustnotes.com.au/>

**Comment by gethryn** [comment]
Correctly converted `<p class="calibre2">The perforated sheet went Whump!-it was a loud bang.</p>` to `<p class="calibre_">The perforated sheet went Whump!—it was a loud bang.</p>`
